# Generated by Django 5.2 on 2026-03-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Unknown Patient', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='urgency_level',
            field=models.IntegerField(default=1, help_text='Higher number = more urgent'),
        ),
    ]
