# Generated by Django 5.2 on 2026-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
